[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target_cpu=native"] 
[target.x86_64-apple-darwin]                                                                                                                         
rustflags = ["-C", "target_cpu=native"] 
